/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./entrypoints/**/*.{html,ts,tsx}",
    "./components/**/*.{html,ts,tsx}",
    "./pages/**/*.{html,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#1f4a68",
        "primary-container": "#b9d9c0",
        "surface-secondary": "#FBFBFA",
        "surface-container-highest": "#e2e3e1",
        "surface": "#f9f9f7",
        "outline-variant": "#c2c8c1",
        "on-primary-container": "#43604c",
        "on-secondary-fixed-variant": "#274f35",
        "surface-dim": "#dadad8",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container": "#eeeeec",
        "accent-pink": "#E38C9D",
        "error-container": "#ffdad6",
        "accent-orange": "#E8A65D",
        "primary-fixed-dim": "#afceb6",
        "accent-purple": "#B69BCB",
        "on-tertiary-fixed": "#001e31",
        "text-secondary": "#707070",
        "on-secondary-container": "#436b4f",
        "on-surface-variant": "#424843",
        "inverse-primary": "#afceb6",
        "inverse-on-surface": "#f1f1ef",
        "text-muted": "#A0A0A0",
        "secondary": "#3f674b",
        "border-subtle": "#E9E9E5",
        "on-primary-fixed": "#042011",
        "tertiary-fixed": "#cbe6ff",
        "outline": "#727972",
        "primary-fixed": "#caebd1",
        "inverse-surface": "#2f3130",
        "tertiary-fixed-dim": "#a3cbef",
        "secondary-fixed-dim": "#a5d1af",
        "primary": "#486551",
        "text-primary": "#242424",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9f7",
        "on-primary-fixed-variant": "#314d3a",
        "tertiary-container": "#add6fa",
        "on-secondary-fixed": "#00210e",
        "secondary-fixed": "#c0edca",
        "secondary-container": "#beebc7",
        "on-background": "#1a1c1b",
        "surface-white": "#FFFFFF",
        "tertiary": "#3a6281",
        "surface-container-high": "#e8e8e6",
        "on-tertiary-container": "#345d7c",
        "error": "#ba1a1a",
        "background": "#f9f9f7",
        "on-secondary": "#ffffff",
        "surface-tint": "#486551",
        "surface-container-low": "#f4f4f2",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1b",
        "surface-variant": "#e2e3e1",
        "warning": "#e8a65d",
        "warning-container": "#ffe8cc",
        "on-warning-container": "#7a4a00",
        "on-warning": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "dock-inset": "24px",
        "max-width-workspace": "1440px",
        "component-padding": "16px",
        "section-gap": "32px",
        "item-gap": "8px",
        "outer-margin": "20px",
        "page-gutter": "20px",
        "page-top": "76px",
        "page-bottom": "128px",
      },
      boxShadow: {
        workspace: "0 10px 30px rgba(0, 0, 0, 0.02)",
        nested: "0 4px 20px rgba(0, 0, 0, 0.05)",
      },
      fontFamily: {
        "body-main": ["Inter", "sans-serif"],
        "headline-page": ["Inter", "sans-serif"],
        "section-title": ["Inter", "sans-serif"],
        "headline-page-mobile": ["Inter", "sans-serif"],
        "display-timer": ["Inter", "sans-serif"],
        "label-secondary": ["Inter", "sans-serif"],
        "caption-metadata": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-main": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-page": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "section-title": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-page-mobile": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "display-timer": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-secondary": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "caption-metadata": ["10px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
